### ISSUE TITLE
More flexible schema declaration

### ISSUE THREAD

**Issue by PaoloAchdjian** [tarantool/tarantool-java#10]
At now (version 1.6.5 of tarantool connector),  the only way to define a schema is use annotate variables whose names are the names used in tarantool.
It should be useful to allowing to pass this information in a programmatic way: for example instead of 
TarantoolConnection16#schema(T schema)
 a method as
TarantoolConnection16#schema(String spaceId, String indexId)
in order to allowing to load this information from a configuration file, for example.

Regards,
Paolo

**Comment by dgreenru** [comment]
I've extracted SchemaResolver in current version and support named indexes and fields.

**Comment by PaoloAchdjian** [comment]
Sorry, bu I doesn't understood what you mean.
I find for a class SchemaResolver in the tarantool connector package but I doesn't find it.

**Comment by dgreenru** [comment]
I can release version 1.6.6 if you want to try it.

**Comment by PaoloAchdjian** [comment]
Ah ok. The current version for me is 1.6.5, for you the developing version it is the current :-)

Thank for the offer, but I'm not in hurry. I prefer use a stable version as it will be used in a software for by my clients. When you think the version 1.6.6 will be ready to release, I will glad to use it.

Anyway, do you have an estimated date for the version 1.6.6 ?

Thanks.
Paolo

**Comment by Totktonada** [comment]
It was implemented in 1.6.6, but then removed in 1.7.0 (66b097537389563ce0d1ac26197843808ec13548). I guess that the reason was incompatibility of the implementation of schema reload with tarantool-1.7*.

Anyway, we implemented this for modern tarantool in the scope of #7 and #137 (in PR #200). It was released in connector-1.9.4.
