### ISSUE TITLE
Clarify TarantoolClusterClient actions when all nodes are down

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-java#126]
The discussion was started [here][1].

[Coveralls][2] helps us understand it is not tested.

The interesting cases are when TarantoolClusterClient.isDead() knows that the connection was closed (all nodes are down in case of the cluster client) at line 48 and when it is not reflected in `state` at the time at line 53. (BTW, it is weird to have two primary sources of this information.) In the former case we'll not add the future to `retries`, but in the latter one we'll do.

```java
 45     @Override
 46     protected boolean isDead(FutureImpl<?> q) {
 47         if ((state.getState() & CLOSED) != 0) {
 48             q.setError(new CommunicationException("Connection is dead", thumbstone));
 49             return true;
 50         }
 51         Exception err = thumbstone;
 52         if (err != null) {
 53             return checkFail(q, err);
 54         }
 55         return false;
 56     }
```

We need to clarify how the cluster client should operate in case of the situation when all nodes are down and test whether resuests will be retried in each of these two cases.

We can trigger line 48 like so:

```diff
diff --git a/src/test/java/org/tarantool/ClientReconnectClusterIT.java b/src/test/java/org/tarantool/ClientReconnectClusterIT.java
index 35737a3..56784a2 100644
--- a/src/test/java/org/tarantool/ClientReconnectClusterIT.java
+++ b/src/test/java/org/tarantool/ClientReconnectClusterIT.java
@@ -108,6 +108,15 @@ public class ClientReconnectClusterIT {
         });
 
         assertEquals("Connection time out.", e.getMessage());
+
+        e = assertThrows(CommunicationException.class, new Executable() {
+            @Override
+            public void execute() throws Throwable {
+                client.syncOps().select(spaceId, pkId, key, 0, 1, Iterator.EQ);
+            }
+        });
+
+        assertEquals("Connection time out.", e.getMessage()); // expected: <Connection time out.> but was: <Connection is dead>
     }
 
     private TarantoolClientImpl makeClient(String...addrs) {
```

[1]: https://github.com/tarantool/tarantool-java/pull/111/#discussion_r250840110
[2]: https://coveralls.io/builds/21257532/source?filename=src/main/java/org/tarantool/TarantoolClusterClient.java#L48

**Comment by nicktorwald** [comment]
Discussed. When a client is closed only thing it should do is to complete a new future exceptionally. There is no sense to check an error transient status and put the future into `retries` because `CLOSED` status is terminal. It leads that the client won't resend anything more being closed.

**Comment by Totktonada** [comment]
It was my misunderstanding. So there is nothing to do here.
