### ISSUE TITLE
How to access to arguments passed to LUA?

### ISSUE THREAD

**Issue by savinov** [tarantool/tarantool-java#14]
TarantoolConnection16Base has this method to execute LUA eval: eval(String expression, Object... args)
But how to access args in LUA?

There is 'arg' variable, but it contain only one entry with tarantool instance name, not the arguments passed to LUA from connector.

**Comment by dgreenru** [comment]
Could u give me code example. I don't understand where u trying to get args?

**Comment by savinov** [comment]
https://github.com/tarantool/tarantool-java/blob/master/src/it/java/org/tarantool/TestClient16.java

Line 51: List eval = con.eval("return ...", 1, 2, 3);

Lets say I want to print arguments 1, 2, 3 to log:

con.eval("log = require('log'); log.info('args0=' .. args[0] .. ' args1=' .. args[1] .. ' args2' .. args[2])", 1, 2, 3);

**Comment by bigbes** [comment]
Arguments are passed into eval command as ellipsis. So your example will look like:
```
tarantool> a:eval("log = require('log'); args = {...}; log.info('args0=' .. args[1] .. ' args1=' .. args[2] .. ' args2' .. args[3])", 1, 2, 3);
2016-07-06 14:54:59.740 [46545] main/114/iproto I> args0=1 args1=2 args23
---
...
```

**Comment by savinov** [comment]
Oh, I see.
Thanks.
