### ISSUE TITLE
Add CI jobs for tarantool 2.1 and 2.2 both

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-java#162]
We have 2x repository for tarantool-2.1 and 2_2 repository for tarantool-2.2 (latter is not released yet) and we need to test both.

I propose to setup two different jobs and set TARANTOOL_REPOSITORY variable for each, then catch this variable value in .travis/travis.pre.sh.

**Comment by nicktorwald** [comment]
What about #52? Did it obsolete? if not, it's better to do them together.

**Comment by Totktonada** [comment]
Ouch, missed that.

Dupe of #52.
