### ISSUE TITLE
Remove TarantoolConnection begin(), commit() and rollback() methods

### ISSUE THREAD

**Issue by isopov** [tarantool/tarantool-java#28]
According to documentation https://tarantool.org/en/doc/1.7/book/box/box_txn_management.html they cannot work and no other connector supports them

**Comment by kostja** [comment]
* Ivan Sopov <notifications@github.com> [17/06/20 20:21]:
> According to documentation https://tarantool.org/en/doc/1.7/book/box/box_txn_management.html they cannot work and no other connector supports them
> 

The patch for this feature is on a branch, soon
begin/commit/rollback will be operational, for vinyl engine at
least.


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
