### ISSUE TITLE
Reconnection process could have synchronization problem: connector is parked, but thumbstone is exception

### ISSUE THREAD

**Issue by yuzhakovsa** [tarantool/tarantool-java#29]
He have caught unexpected state at client: thumbstone is exception, but connector thread was parked.
I guess, this state probably could happen like this:
Write thread: exception
Write thread: die
Write thread: interruption signal to write thread
Write thread: unpark connector
Connector: connect
Connector: thumbstone = null
Read thread: have interrupted signal, but is not yet interrupted
Read thread: exception
Read thread: die (thumbstone is null, so will make stopIO and set thumstone to new exception)
Connector: finish execution and park
Result: connector is parked and thumbstone is exception (means that exec with throw exception)

Review this case, please.

**Comment by dgreenru** [comment]
Thank you, will investigate this case

**Comment by dgreenru** [comment]
I'll fix this in next release. 
To quick fix this issue in your code you could add field CountDownLatch stop to client. Then
override stopIO() and add 
`stop = new CountDownLatch(2);` before and `stop.await()` after the base method.
 Also you could add `stop.countDown(); `at the end of overridden readThread and writeThread.

**Comment by dgreenru** [comment]
fixed in 1.7.5. Artifact will be available in the the central in couple of hours.
