### ISSUE TITLE
Add built-in SocketCahnnelProvider, implementing round-robin between several tarantool instances

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool-java#37]
Use-case: tarantool is deployed as a geo-distributed cluster, and when one DC goes down, application must switch to reserve DC with minimal service disruption.

Proposal: add built-in Provider which would take several connection URI's as a config, and would quickly try to establish connection to them in a circle, returning the first succesful one.
Edge-case: if all URIs are unavailable, return error.

Such Provider could be used straight-away in described use-case, and would be also useful as a demo of more advanced connection strategies.

**Comment by Totktonada** [comment]
* Similar tarantool-python issue: https://github.com/tarantool/tarantool-python/issues/106
* Similar go-tarantool issue: https://github.com/tarantool/go-tarantool/issues/68

**Comment by Totktonada** [comment]
@sharonovd It is unclear whether it is needed for org.tarantool.TarantoolConnection (basic connector functionality) or java.sql.Connection (JDBC).

**Comment by sharonovd** [comment]
@Totktonada basic
