### ISSUE TITLE
Releasing to Maven Central Repo

### ISSUE THREAD

**Issue by rukbat** [tarantool/tarantool-java#4]
Hi,
are you planning to release tarantool-java to maven central in the near future?

I cannot consume external SNAPSHOT version in my project and having release version would be helpful.

**Comment by dgreenru** [comment]
Hi,

**Comment by dgreenru** [comment]
I've just pushed to sonatype staging repo and now waiting for review and sync with central. You can track progress here https://issues.sonatype.org/browse/OSSRH-18205

**Comment by dgreenru** [comment]
done :)

**Comment by rukbat** [comment]
Thank you @dgreenru
