### ISSUE TITLE
jdbc: resultset metadata is incorrect

### ISSUE THREAD

**Issue by ztarvos** [tarantool/tarantool-java#42]
The following API methods appear to be implemented but do not actually work.

ResultSetMetaData.getColumnCount() returns wrong number of columns.
ResultSetMetaData.getColumnName() returns null.

**Comment by kyukhin** [comment]
Fixed by 8aad0073533fb71b09a2bbf02765e6ce2e1edb01

**Comment by Totktonada** [comment]
The patch discussion thread: https://www.freelists.org/post/tarantool-patches/PATCH-jdbc-fix-NPE-in-update
