### ISSUE TITLE
jdbc: BLOB type roundtrip fails

### ISSUE THREAD

**Issue by ztarvos** [tarantool/tarantool-java#45]
Values of BINARY/VARBINARY columns are selected back as strings when initially inserted as byte arrays in a prepared statement.

`CREATE TABLE testbin(id INT PRIMARY KEY, b VARBINARY)`

`PreparedStatement prep = conn.prepareStatement("INSERT INTO testbin(id, b) VALUES (1, ?)");`
`prep.setBytes(1, new BigInteger("ABCD", 16).toByteArray());`
`prep.executeUpdate();`
`...`
`ResultSet rs = stmt.executeQuery("SELECT b FROM testbin");`
`rs.next();`
`rs.getBytes(1) - fails.`

`Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to [B
        at org.tarantool.jdbc.SQLResultSet.getBytes(SQLResultSet.java:133)
        at TestJdbcBinary.main(TestJdbcBinary.java:32)`

But when inserted as X’hexstring’ in a basic statement, the value that gets back is byte[].

`INSERT INTO testbin(id, b) VALUES(1, X'ABCD') -- OK, select returns byte[]`

**Comment by Totktonada** [comment]
Confirmed on Tarantool 2.1.1-164-gf6a31c034. Commented here: https://github.com/tarantool/tarantool/issues/3650#issuecomment-450529607

**Comment by Totktonada** [comment]
The Java connector correclty sends bin8 type in the case, but tarantool stores fixstr and responds with fixint. So this is blocked on https://github.com/tarantool/tarantool/issues/3650

**Comment by nicktorwald** [comment]
Nothing has changed after applying the recent Tarantool changes made in scope of tarantool/tarantool#4019 .
The client still receives blob data as a string and a column type as a `BLOB` instead of `SCALAR`.

**Comment by Totktonada** [comment]
Now it is blocked by the problem described [here][1].

[1]: https://github.com/tarantool/tarantool/issues/3650#issuecomment-471850969

**Comment by Totktonada** [comment]
The tarantool side of the issue was resolved in 2.1.1-423-g4007436aa ( https://github.com/tarantool/tarantool/commit/4007436aa1746e7701d1367d903fad96594851d4 ). Not blocked now.
