### ISSUE TITLE
1.6.5 schema can't initialize with tarantool 1.6.7

### ISSUE THREAD

**Issue by bashnesnos** [tarantool/tarantool-java#6]
I need a hand here, it seems I'm getting things wrong.

I'm constantly getting the following after auth:
```
java.lang.IllegalStateException: Can't find field id customer.accountId

	at org.tarantool.TarantoolConnection16Base.schema(TarantoolConnection16Base.java:214)
```

I thought ok, may be there is no meta data because there is no data in the space. So I've added a record with all fields, but the error persists.

So how is it supposed to work? Tarantool records are tuples, where I can store any amount of fields, so I thought fields in the field-mapping are basically an enumeration, where only order counts. Where I'm wrong?

**Comment by dgreenru** [comment]
Did u forget space.format? Look at box.space.tester:format at https://github.com/tarantool/tarantool-java/blob/master/src/it/java/org/tarantool/TestClient16.java

**Comment by bashnesnos** [comment]
Correct, I missed that. Cheers!

**Comment by dgreenru** [comment]
Please use stackoverflow with tags tarnatool and java for questions like this.

**Comment by bashnesnos** [comment]
No problems, here you go: http://stackoverflow.com/questions/33956003/schema-cant-initialize-with-cant-find-field-id-exception
