### ISSUE TITLE
jdbc: Support isWrapperFor() and unwrap() methods

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-java#73]
It is required by the JDBC standard.

**Comment by nicktorwald** [comment]
It's required to be implemented at least by following interfaces from the `java.sql` package
```text
Connection
Statement,
PreparedStatement
CallableStatement
DatabaseMetaData
ParameterMetaData
ResultSetMetaData
ResultSet
```

**Comment by nicktorwald** [comment]
Connection, Statement, PreparedStatement, and CallableStatement have been already done in the scope of #87
