### ISSUE TITLE
jdbc: Support resultSetConsurrency parameter in Connection methods

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-java#86]
The following functions should be implemented (should not raise SQLFeatureNotSupportedException when called with supported resultSetConcurrency value, referenced as `concurrency` below):

* `createStatement(type, concurrency)`
* `createStatement(type, concurrency, holdability)`
* `prepareCall(sql, type, concurrency)`
* `prepareCall(sql, type, concurrency, holdability)`
* `prepareStatement(sql, type, concurrency)`
* `prepareStatement(sql, type, concurrency, holdability)`

The `DatabaseMetadata.supportsResultSetConcurrency(type, holdability)` should return appropriate values for both `ResultSet.CONCUR_READ_ONLY` and `ResultSet.CONCUR_UPDATABLE` in combination with passed resultSetType (see #85).

The issue is about proper APIs support, so it seems that in the scope of this issue `ResultSet.CONCUR_READ_ONLY` support is enough.

**Comment by nicktorwald** [comment]
Closed by #151
