### ISSUE TITLE
tarantool java connector and composite index

### ISSUE THREAD

**Issue by PaoloAchdjian** [tarantool/tarantool-java#9]
Hi,

I'm using the java connector (version 1.6.5) to connected to tarantool (version 1.6.7 on ubuntu)  with a simple configuration as

selection_session_space = box.schema.space.create('selection', {temporary = true})

box.space.selection:format{
    {name='id',type='num'},
    {name='isTest',type='num'},
    {name='ttl',type='num'}
    }

If I using a simple index as

selection_session_space:create_index('indexId', {
             type = 'HASH',
             parts = {1, 'num'}
             })

all works fine.
But if I using an composite index as

 selection_session_space:create_index('indexId', {
             type = 'HASH',
             parts = {1, 'num',2, 'num'}
             })

The connector throw a NullPointerException at (TarantoolConnection16Base.java:196) when I select the schema with 
TarantoolConnection16.schema(schema);

**Comment by dgreenru** [comment]
Hi could u show me your schema object?

**Comment by PaoloAchdjian** [comment]
Thank for fast replay.

bellow the class you requested


public class SelectionSchema {
    @Space(value = "selection")
    public SpaceWithPK selectionSpace = new SpaceWithPK();

    public class SpaceWithPK {
        @SpaceId
        public int id;

        @IndexId
        public int indexId;

        @Override
        public String toString() {
            return "SpaceWithPK{" + "id=" + id + ", indexId=" + indexId + "}";
        }
    }

    @Override
    public String toString() {
        return "ApiSoapSelectionSchema{" + "api=" + selectionSpace + "}";
    }
}

**Comment by dgreenru** [comment]
I've written the test below and execute it uses connector-1.6.5 and it works. Could you try the same?
Could you show me output of
```lua
box.space._vspace:select{}
```
and

```lua
box.space._vindex:select{}
```



You also could try to run the test below with fresh tarantool
```java
package org.tarantool;

import java.io.IOException;

import org.tarantool.schema.IndexId;
import org.tarantool.schema.Space;
import org.tarantool.schema.SpaceId;

public class Test {
    /**
     * space = box.schema.space.create('selection')
     * box.space.selection:format{
     * {name='id',type='num'},
     * {name='isTest',type='num'},
     * {name='ttl',type='num'}
     * }
     *
     * box.space.selection:create_index('indexId', {
     * type = 'HASH',
     * parts = {1, 'num',2, 'num'}
     * });
     */

    public static class SelectionSchema {
        @Space(value = "selection")
        public SpaceWithPK selectionSpace = new SpaceWithPK();

        public static class SpaceWithPK {
            @SpaceId
            public int id;

            @IndexId
            public int indexId;

            @Override
            public String toString() {
                return "SpaceWithPK{" + "id=" + id + ", indexId=" + indexId + "}";
            }
        }

        @Override
        public String toString() {
            return "ApiSoapSelectionSchema{" + "api=" + selectionSpace + "}";
        }
    }

    public static void main(String[] args) throws IOException {
        TarantoolConnection16 con = new TarantoolConnection16Impl("localhost", 3301);
        con.auth("test", "test");
        final SelectionSchema schema = con.schema(new SelectionSchema());
        System.out.printf(schema.selectionSpace.toString());
        con.close();

    }
}
```

**Comment by PaoloAchdjian** [comment]
I understood the problem. It is my fault. There was mismatch from the index name in tarantool and that used in java code.

Thanks.
