### ISSUE TITLE
constructor org.tarantool.TarantoolClientImpl#TarantoolClientImpl throws NullPointerException

### ISSUE THREAD

**Issue by nikvs84** [tarantool/tarantool-java#94]
Tarantool version: 1.9

OS version: Java connector: Win 10 x64
Java connector version: 1.7.5

Bug description: constructor org.tarantool.TarantoolClientImpl#TarantoolClientImpl throws NPE

Steps to reproduce:
Try to create a client on a port where there is no Tarantool server

`   
     
        connector.start();
        try {
            if (!waitAlive(config.initTimeoutMillis, TimeUnit.MILLISECONDS)) {
                 close(); // NPE is thrown here from the method 'stopIO'
                throw new CommunicationException(config.initTimeoutMillis+"ms is exceeded when waiting for client initialization. You could configure init timeout in TarantoolConfig");
            }
        } catch (InterruptedException e) {

`
method org.tarantool.TarantoolClientImpl#stopIO throws NPE
`

        closeChannel(channel);
        try {
            stopIO.await(); // stopIO == null
        } catch (InterruptedException ignored) {

        }

`

**Comment by Totktonada** [comment]
@ztarvos You recently rewrote the relevant synchronization code. Can you, please, verify whether this bug is actual for the current master?

**Comment by Totktonada** [comment]
Thanks!

We need to release the new version…

**Comment by nikvs84** [comment]
Will there be a new release of java connector with the correction of this error?

**Comment by Totktonada** [comment]
Sure. Within days.

**Comment by Totktonada** [comment]
Released 1.8.0.
